/* Wort-Zwillinge (Task 53): German words that are easy to mix up.
   type: 'look' = look almost the same · 'sound' = sound almost the same · 'article' = same word, other article = other meaning
         'false' = false friend for English speakers · 'meaning' = similar meaning, different use
   Each group: { id, type, tip (how to tell them apart), tip_ta, words: [{ de, art, en, ta, pic, ex, ex_en }] }
   Tamil and examples written with AI assistance and reviewed; checked by scripts/check_confusables.py. */
window.DC_CONFUSABLES = [
  { id: 'kueche', type: 'look', tip: 'Küche has ü and ends in -che (KÜ-che). Kuchen has u and ends in -chen (KU-chen). kochen is the verb "to cook": you kochen in the Küche and bake a Kuchen.',
    tip_ta: 'Küche (ü) = சமையலறை; Kuchen (u, -chen) = கேக்; kochen = சமை. சமையலறையில் சமைத்து கேக் செய்கிறோம்!',
    words: [{ de: 'Küche', art: 'die', en: 'kitchen', ta: 'சமையலறை', pic: '🍳', ex: 'Ich koche in der Küche.', ex_en: 'I cook in the kitchen.' },
      { de: 'Kuchen', art: 'der', en: 'cake', ta: 'கேக்', pic: '🍰', ex: 'Der Kuchen ist lecker.', ex_en: 'The cake is tasty.' },
      { de: 'kochen', art: '', en: 'to cook', ta: 'சமை', pic: '🧑‍🍳', ex: 'Wir kochen heute Reis.', ex_en: 'We are cooking rice today.' }] },
  { id: 'kirche', type: 'look', tip: 'Kirsche has an extra s: Kir-S-che. The cherry (Kirsche) is small — the church (Kirche) is big and has no s.',
    tip_ta: 'Kirsche-ல் கூடுதல் „s“ = செர்ரிப் பழம்; Kirche = தேவாலயம்.',
    words: [{ de: 'Kirche', art: 'die', en: 'church', ta: 'தேவாலயம்', pic: '⛪', ex: 'Die Kirche ist sehr alt.', ex_en: 'The church is very old.' },
      { de: 'Kirsche', art: 'die', en: 'cherry', ta: 'செர்ரிப் பழம்', pic: '🍒', ex: 'Die Kirschen sind rot.', ex_en: 'The cherries are red.' }] },
  { id: 'schon', type: 'look', tip: 'schön with ö = beautiful. schon without dots = already. The dots are the "eyes" that see something beautiful.',
    tip_ta: 'schön (ö) = அழகான; schon = ஏற்கனவே.',
    words: [{ de: 'schön', art: '', en: 'beautiful', ta: 'அழகான', pic: '🌸', ex: 'Das Wetter ist schön.', ex_en: 'The weather is nice.' },
      { de: 'schon', art: '', en: 'already', ta: 'ஏற்கனவே', pic: '✅', ex: 'Ich habe schon gegessen.', ex_en: 'I have already eaten.' }] },
  { id: 'zahlen', type: 'look', tip: 'zahlen (no dots) = pay with money (die Zahlung). zählen (ä) = count numbers (1, 2, 3). erzählen = tell a story.',
    tip_ta: 'zahlen = பணம் செலுத்து; zählen (ä) = எண்ணு; erzählen = கதை சொல்.',
    words: [{ de: 'zahlen', art: '', en: 'to pay', ta: 'பணம் செலுத்து', pic: '💳', ex: 'Ich möchte zahlen, bitte.', ex_en: 'I would like to pay, please.' },
      { de: 'zählen', art: '', en: 'to count', ta: 'எண்ணு', pic: '🔢', ex: 'Das Kind zählt bis zehn.', ex_en: 'The child counts to ten.' },
      { de: 'erzählen', art: '', en: 'to tell (a story)', ta: 'கதை சொல்', pic: '📖', ex: 'Oma erzählt eine Geschichte.', ex_en: 'Grandma tells a story.' }] },
  { id: 'druecken', type: 'look', tip: 'drücken (ü) = press / push (a button, a door). drucken (u) = print (der Drucker = printer). On doors: "Drücken" = push, "Ziehen" = pull.',
    tip_ta: 'drücken (ü) = அழுத்து / தள்ளு; drucken (u) = அச்சிடு.',
    words: [{ de: 'drücken', art: '', en: 'to press, push', ta: 'அழுத்து / தள்ளு', pic: '👉', ex: 'Drücken Sie den Knopf.', ex_en: 'Press the button.' },
      { de: 'drucken', art: '', en: 'to print', ta: 'அச்சிடு', pic: '🖨️', ex: 'Ich drucke das Formular.', ex_en: 'I am printing the form.' }] },
  { id: 'fuehlen', type: 'look', tip: 'fühlen (üh, long) = feel. füllen (üll, short) = fill (voll = full). fallen = fall; fällen = cut down a tree.',
    tip_ta: 'fühlen = உணர்; füllen = நிரப்பு.',
    words: [{ de: 'fühlen', art: '', en: 'to feel', ta: 'உணர்', pic: '🙂', ex: 'Ich fühle mich gut.', ex_en: 'I feel good.' },
      { de: 'füllen', art: '', en: 'to fill', ta: 'நிரப்பு', pic: '🫗', ex: 'Er füllt das Glas mit Wasser.', ex_en: 'He fills the glass with water.' }] },
  { id: 'tasche', type: 'look', tip: 'Tasche (sch) = bag. Tasse (ss) = cup. Taste (st) = key / button (on a keyboard).',
    tip_ta: 'Tasche = பை; Tasse = கோப்பை; Taste = விசை / பொத்தான்.',
    words: [{ de: 'Tasche', art: 'die', en: 'bag', ta: 'பை', pic: '👜', ex: 'Meine Tasche ist schwer.', ex_en: 'My bag is heavy.' },
      { de: 'Tasse', art: 'die', en: 'cup', ta: 'கோப்பை', pic: '☕', ex: 'Eine Tasse Tee, bitte.', ex_en: 'A cup of tea, please.' },
      { de: 'Taste', art: 'die', en: 'key, button', ta: 'விசை / பொத்தான்', pic: '⌨️', ex: 'Drück die Taste „Enter“.', ex_en: 'Press the Enter key.' }] },
  { id: 'strasse', type: 'look', tip: 'Straße (ß) = street. Strafe (f) = punishment / fine. Strand = beach.',
    tip_ta: 'Straße = தெரு; Strafe = தண்டனை / அபராதம்; Strand = கடற்கரை.',
    words: [{ de: 'Straße', art: 'die', en: 'street', ta: 'தெரு', pic: '🛣️', ex: 'Ich wohne in der Goethestraße.', ex_en: 'I live on Goethe Street.' },
      { de: 'Strafe', art: 'die', en: 'punishment, fine', ta: 'தண்டனை / அபராதம்', pic: '🚨', ex: 'Falschparken kostet eine Strafe.', ex_en: 'Wrong parking costs a fine.' },
      { de: 'Strand', art: 'der', en: 'beach', ta: 'கடற்கரை', pic: '🏖️', ex: 'Wir liegen am Strand.', ex_en: 'We are lying on the beach.' }] },
  { id: 'glas', type: 'look', tip: 'Glas (l) = glass. Gras (r) = grass. Gast = guest.',
    tip_ta: 'Glas = கண்ணாடி / டம்ளர்; Gras = புல்.',
    words: [{ de: 'Glas', art: 'das', en: 'glass', ta: 'கண்ணாடி டம்ளர்', pic: '🥛', ex: 'Ein Glas Wasser, bitte.', ex_en: 'A glass of water, please.' },
      { de: 'Gras', art: 'das', en: 'grass', ta: 'புல்', pic: '🌱', ex: 'Die Kühe fressen Gras.', ex_en: 'The cows eat grass.' }] },
  { id: 'leben', type: 'look', tip: 'leben (e) = live. lieben (ie) = love. loben (o) = praise. Remember: "Ich liebe dich" — the ie is in love.',
    tip_ta: 'leben = வாழ்; lieben = நேசி / காதலி; loben = புகழ்.',
    words: [{ de: 'leben', art: '', en: 'to live', ta: 'வாழ்', pic: '🌱', ex: 'Ich lebe in Deutschland.', ex_en: 'I live in Germany.' },
      { de: 'lieben', art: '', en: 'to love', ta: 'நேசி', pic: '❤️', ex: 'Ich liebe meine Familie.', ex_en: 'I love my family.' },
      { de: 'loben', art: '', en: 'to praise', ta: 'புகழ்', pic: '👏', ex: 'Die Lehrerin lobt den Schüler.', ex_en: 'The teacher praises the pupil.' }] },
  { id: 'lesen', type: 'look', tip: 'lesen (e) = read. lösen (ö) = solve (die Lösung). löschen (ö + sch) = delete / put out a fire (die Feuerwehr löscht).',
    tip_ta: 'lesen = படி; lösen = தீர்; löschen = அழி / அணை.',
    words: [{ de: 'lesen', art: '', en: 'to read', ta: 'படி', pic: '📖', ex: 'Ich lese ein Buch.', ex_en: 'I am reading a book.' },
      { de: 'lösen', art: '', en: 'to solve', ta: 'தீர்', pic: '🧩', ex: 'Wir lösen das Problem.', ex_en: 'We solve the problem.' },
      { de: 'löschen', art: '', en: 'to delete, extinguish', ta: 'அழி / அணை', pic: '🧯', ex: 'Ich lösche die Datei.', ex_en: 'I delete the file.' }] },
  { id: 'stadt', type: 'sound', tip: 'All sound "shtat". Stadt (dt) = city. Staat (aa, long) = state / country. statt = instead of.',
    tip_ta: 'Stadt = நகரம்; Staat = நாடு / அரசு; statt = பதிலாக.',
    words: [{ de: 'Stadt', art: 'die', en: 'city, town', ta: 'நகரம்', pic: '🏙️', ex: 'Berlin ist eine große Stadt.', ex_en: 'Berlin is a big city.' },
      { de: 'Staat', art: 'der', en: 'state, country', ta: 'நாடு / அரசு', pic: '🏛️', ex: 'Der Staat zahlt Kindergeld.', ex_en: 'The state pays child benefit.' },
      { de: 'statt', art: '', en: 'instead of', ta: 'பதிலாக', pic: '🔄', ex: 'Ich trinke Tee statt Kaffee.', ex_en: 'I drink tea instead of coffee.' }] },
  { id: 'rat', type: 'sound', tip: 'Both sound "raat" (d at the end sounds like t). Rat = advice (raten). Rad = wheel / bike (das Fahrrad).',
    tip_ta: 'Rat = ஆலோசனை; Rad = சக்கரம் / சைக்கிள்.',
    words: [{ de: 'Rat', art: 'der', en: 'advice', ta: 'ஆலோசனை', pic: '💡', ex: 'Kannst du mir einen Rat geben?', ex_en: 'Can you give me some advice?' },
      { de: 'Rad', art: 'das', en: 'wheel, bike', ta: 'சக்கரம் / சைக்கிள்', pic: '🚲', ex: 'Ich fahre mit dem Rad zur Arbeit.', ex_en: 'I ride my bike to work.' }] },
  { id: 'mehr', type: 'sound', tip: 'mehr = more. Meer = sea (the ee is like waves). Mehl = flour (for baking a Kuchen!).',
    tip_ta: 'mehr = அதிகம்; Meer = கடல்; Mehl = மாவு.',
    words: [{ de: 'mehr', art: '', en: 'more', ta: 'அதிகம்', pic: '➕', ex: 'Ich möchte mehr Zeit.', ex_en: 'I would like more time.' },
      { de: 'Meer', art: 'das', en: 'sea', ta: 'கடல்', pic: '🌊', ex: 'Im Sommer fahren wir ans Meer.', ex_en: 'In summer we go to the sea.' },
      { de: 'Mehl', art: 'das', en: 'flour', ta: 'மாவு', pic: '🌾', ex: 'Für den Kuchen brauche ich Mehl.', ex_en: 'I need flour for the cake.' }] },
  { id: 'vier', type: 'sound', tip: 'vier (4) and für (for) sound almost the same — vier has a long "ee", für has the rounded ü. Feuer = fire.',
    tip_ta: 'vier = நான்கு; für = க்காக; Feuer = நெருப்பு.',
    words: [{ de: 'vier', art: '', en: 'four', ta: 'நான்கு', pic: '4️⃣', ex: 'Ich habe vier Kinder.', ex_en: 'I have four children.' },
      { de: 'für', art: '', en: 'for', ta: '-க்காக', pic: '🎁', ex: 'Das Geschenk ist für dich.', ex_en: 'The present is for you.' },
      { de: 'Feuer', art: 'das', en: 'fire', ta: 'நெருப்பு', pic: '🔥', ex: 'Das Feuer ist heiß.', ex_en: 'The fire is hot.' }] },
  { id: 'tuer', type: 'sound', tip: 'Tür (ü) = door. Tier (ie) = animal. Round your lips for ü: Tür.',
    tip_ta: 'Tür (ü) = கதவு; Tier (ie) = விலங்கு.',
    words: [{ de: 'Tür', art: 'die', en: 'door', ta: 'கதவு', pic: '🚪', ex: 'Mach bitte die Tür zu.', ex_en: 'Please close the door.' },
      { de: 'Tier', art: 'das', en: 'animal', ta: 'விலங்கு', pic: '🐾', ex: 'Der Hund ist mein Lieblingstier.', ex_en: 'The dog is my favourite animal.' }] },
  { id: 'nacht', type: 'sound', tip: 'Nacht (ch) = night. nach = to / after. nackt (ck-t) = naked — be careful with this one!',
    tip_ta: 'Nacht = இரவு; nach = பிறகு / -க்கு; nackt = நிர்வாணம்.',
    words: [{ de: 'Nacht', art: 'die', en: 'night', ta: 'இரவு', pic: '🌙', ex: 'Gute Nacht!', ex_en: 'Good night!' },
      { de: 'nach', art: '', en: 'after, to', ta: 'பிறகு / -க்கு', pic: '➡️', ex: 'Nach dem Essen fahre ich nach Hause.', ex_en: 'After the meal I go home.' }] },
  { id: 'ei', type: 'sound', tip: 'Ei = egg. Eis = ice / ice cream (with s). Eins = one.',
    tip_ta: 'Ei = முட்டை; Eis = பனிக்கட்டி / ஐஸ்கிரீம்.',
    words: [{ de: 'Ei', art: 'das', en: 'egg', ta: 'முட்டை', pic: '🥚', ex: 'Zum Frühstück esse ich ein Ei.', ex_en: 'I eat an egg for breakfast.' },
      { de: 'Eis', art: 'das', en: 'ice, ice cream', ta: 'ஐஸ்கிரீம் / பனிக்கட்டி', pic: '🍦', ex: 'Die Kinder essen Eis.', ex_en: 'The children eat ice cream.' }] },
  { id: 'zehn', type: 'sound', tip: 'zehn = ten. Zehe = toe (on the foot). sehen = see (s sounds like English z!).',
    tip_ta: 'zehn = பத்து; Zehe = கால் விரல்; sehen = பார்.',
    words: [{ de: 'zehn', art: '', en: 'ten', ta: 'பத்து', pic: '🔟', ex: 'Es ist zehn Uhr.', ex_en: 'It is ten o\'clock.' },
      { de: 'Zehe', art: 'die', en: 'toe', ta: 'கால் விரல்', pic: '🦶', ex: 'Meine Zehe tut weh.', ex_en: 'My toe hurts.' },
      { de: 'sehen', art: '', en: 'to see', ta: 'பார்', pic: '👀', ex: 'Ich sehe dich morgen.', ex_en: 'I\'ll see you tomorrow.' }] },
  { id: 'wetter', type: 'sound', tip: 'Wetter (e, tt) = weather. wieder (ie) = again (Auf Wiedersehen = see you again). Wasser = water.',
    tip_ta: 'Wetter = வானிலை; wieder = மீண்டும்.',
    words: [{ de: 'Wetter', art: 'das', en: 'weather', ta: 'வானிலை', pic: '🌦️', ex: 'Das Wetter ist heute schlecht.', ex_en: 'The weather is bad today.' },
      { de: 'wieder', art: '', en: 'again', ta: 'மீண்டும்', pic: '🔁', ex: 'Komm bald wieder!', ex_en: 'Come again soon!' }] },
  { id: 'bitten', type: 'sound', tip: 'bitten (i) = ask for, request (bitte!). bieten (ie) = offer (das Angebot). beten (e) = pray. Bett = bed.',
    tip_ta: 'bitten = கேள் / வேண்டு; bieten = வழங்கு; beten = பிரார்த்தனை செய்.',
    words: [{ de: 'bitten', art: '', en: 'to ask (for), request', ta: 'வேண்டு / கேள்', pic: '🙏', ex: 'Ich bitte dich um Hilfe.', ex_en: 'I ask you for help.' },
      { de: 'bieten', art: '', en: 'to offer', ta: 'வழங்கு', pic: '🤲', ex: 'Die Firma bietet einen Kurs an.', ex_en: 'The company offers a course.' },
      { de: 'beten', art: '', en: 'to pray', ta: 'பிரார்த்தனை செய்', pic: '🛐', ex: 'Sie betet jeden Abend.', ex_en: 'She prays every evening.' }] },
  { id: 'mann', type: 'sound', tip: 'Mann (nn, capital) = man / husband. man (small, one n) = one / people in general. Mond = moon.',
    tip_ta: 'Mann = ஆண் / கணவர்; man = ஒருவர் (பொதுவாக).',
    words: [{ de: 'Mann', art: 'der', en: 'man, husband', ta: 'ஆண் / கணவர்', pic: '👨', ex: 'Mein Mann arbeitet bei Bosch.', ex_en: 'My husband works at Bosch.' },
      { de: 'man', art: '', en: 'one, you (in general)', ta: 'ஒருவர் (பொதுவாக)', pic: '👥', ex: 'Hier darf man nicht rauchen.', ex_en: 'You are not allowed to smoke here.' }] },
  { id: 'see', type: 'article', tip: 'Same word, different article, different meaning: der See = lake (inland), die See = the sea (die Nordsee, die Ostsee).',
    tip_ta: 'der See = ஏரி; die See = கடல். article மாறினால் அர்த்தம் மாறும்!',
    words: [{ de: 'See', art: 'der', en: 'lake', ta: 'ஏரி', pic: '🏞️', ex: 'Wir schwimmen im See.', ex_en: 'We swim in the lake.' },
      { de: 'See', art: 'die', en: 'sea', ta: 'கடல்', pic: '🌊', ex: 'Hamburg liegt nicht direkt an der See.', ex_en: 'Hamburg is not directly by the sea.' }] },
  { id: 'leiter', type: 'article', tip: 'der Leiter = the leader / manager (a person, der). die Leiter = the ladder (a thing).',
    tip_ta: 'der Leiter = தலைவர் / மேலாளர்; die Leiter = ஏணி.',
    words: [{ de: 'Leiter', art: 'der', en: 'leader, manager', ta: 'தலைவர் / மேலாளர்', pic: '👔', ex: 'Der Leiter der Schule heißt Herr Kurz.', ex_en: 'The head of the school is called Mr Kurz.' },
      { de: 'Leiter', art: 'die', en: 'ladder', ta: 'ஏணி', pic: '🪜', ex: 'Er steigt auf die Leiter.', ex_en: 'He climbs up the ladder.' }] },
  { id: 'band', type: 'article', tip: 'das Band = ribbon / tape. die Band = music group (English word). der Band = volume (one book of a series).',
    tip_ta: 'das Band = நாடா; die Band = இசைக்குழு; der Band = நூலின் தொகுதி.',
    words: [{ de: 'Band', art: 'das', en: 'ribbon, tape', ta: 'நாடா', pic: '🎀', ex: 'Das Geschenk hat ein rotes Band.', ex_en: 'The present has a red ribbon.' },
      { de: 'Band', art: 'die', en: 'band (music)', ta: 'இசைக்குழு', pic: '🎸', ex: 'Die Band spielt heute Abend.', ex_en: 'The band is playing tonight.' },
      { de: 'Band', art: 'der', en: 'volume (book)', ta: 'நூல் தொகுதி', pic: '📚', ex: 'Ich lese den zweiten Band.', ex_en: 'I am reading the second volume.' }] },
  { id: 'teil', type: 'article', tip: 'der Teil = part (of something bigger). das Teil = a (single) piece / thing (colloquial: Das Teil ist kaputt).',
    tip_ta: 'der Teil = பகுதி; das Teil = ஒரு பொருள் / துண்டு.',
    words: [{ de: 'Teil', art: 'der', en: 'part', ta: 'பகுதி', pic: '🧩', ex: 'Der erste Teil des Films war gut.', ex_en: 'The first part of the film was good.' },
      { de: 'Teil', art: 'das', en: 'piece, (spare) part', ta: 'உதிரிப் பாகம் / பொருள்', pic: '🔩', ex: 'Das Ersatzteil kommt morgen.', ex_en: 'The spare part is coming tomorrow.' }] },
  { id: 'bekommen', type: 'false', tip: 'bekommen does NOT mean "become"! bekommen = get / receive. "become" = werden.',
    tip_ta: 'bekommen = பெறு (become அல்ல!); werden = ஆகு.',
    words: [{ de: 'bekommen', art: '', en: 'to get, receive', ta: 'பெறு', pic: '📬', ex: 'Ich bekomme einen Brief.', ex_en: 'I receive a letter.' },
      { de: 'werden', art: '', en: 'to become', ta: 'ஆகு', pic: '🌱', ex: 'Ich möchte Ärztin werden.', ex_en: 'I would like to become a doctor.' }] },
  { id: 'gift', type: 'false', tip: 'das Gift = poison (!), not a present. A present is das Geschenk.',
    tip_ta: 'Gift = விஷம் (பரிசு அல்ல!); Geschenk = பரிசு.',
    words: [{ de: 'Gift', art: 'das', en: 'poison', ta: 'விஷம்', pic: '☠️', ex: 'Vorsicht, das ist Gift!', ex_en: 'Careful, that is poison!' },
      { de: 'Geschenk', art: 'das', en: 'present, gift', ta: 'பரிசு', pic: '🎁', ex: 'Danke für das Geschenk!', ex_en: 'Thanks for the present!' }] },
  { id: 'wer', type: 'false', tip: 'wer = WHO (not "where"). wo = WHERE. Think: wo = where, wer = who.',
    tip_ta: 'wer = யார்; wo = எங்கே. ஆங்கில "where" ஐப் போல் தோன்றினாலும் wer = யார்!',
    words: [{ de: 'wer', art: '', en: 'who', ta: 'யார்', pic: '🧍', ex: 'Wer ist das?', ex_en: 'Who is that?' },
      { de: 'wo', art: '', en: 'where', ta: 'எங்கே', pic: '📍', ex: 'Wo wohnst du?', ex_en: 'Where do you live?' }] },
  { id: 'also', type: 'false', tip: 'also = so / therefore (not "also"). "also / too" = auch.',
    tip_ta: 'also = ஆகவே; auch = கூட / மேலும்.',
    words: [{ de: 'also', art: '', en: 'so, therefore', ta: 'ஆகவே', pic: '👉', ex: 'Es regnet, also nehme ich den Bus.', ex_en: 'It\'s raining, so I\'ll take the bus.' },
      { de: 'auch', art: '', en: 'also, too', ta: 'கூட / மேலும்', pic: '➕', ex: 'Ich komme auch mit.', ex_en: 'I\'m coming too.' }] },
  { id: 'handy', type: 'false', tip: 'das Handy = mobile phone (a German invention, not "handy"). "handy / practical" = praktisch.',
    tip_ta: 'Handy = கைபேசி; praktisch = பயனுள்ள / வசதியான.',
    words: [{ de: 'Handy', art: 'das', en: 'mobile phone', ta: 'கைபேசி', pic: '📱', ex: 'Mein Handy ist leer.', ex_en: 'My phone battery is empty.' },
      { de: 'praktisch', art: '', en: 'handy, practical', ta: 'வசதியான', pic: '🧰', ex: 'Die Tasche ist sehr praktisch.', ex_en: 'The bag is very handy.' }] },
  { id: 'chef', type: 'false', tip: 'der Chef = boss (not a cook). A cook is der Koch / die Köchin.',
    tip_ta: 'Chef = மேலதிகாரி; Koch = சமையல்காரர்.',
    words: [{ de: 'Chef', art: 'der', en: 'boss', ta: 'மேலதிகாரி', pic: '👔', ex: 'Mein Chef ist heute nicht da.', ex_en: 'My boss isn\'t here today.' },
      { de: 'Koch', art: 'der', en: 'cook, chef', ta: 'சமையல்காரர்', pic: '🧑‍🍳', ex: 'Der Koch macht eine Suppe.', ex_en: 'The cook is making a soup.' }] },
  { id: 'kennen', type: 'meaning', tip: 'kennen = know a person / place / thing (be familiar). wissen = know a fact (… dass, wo, wann). können = can.',
    tip_ta: 'kennen = அறிந்திரு (நபர் / இடம்); wissen = தெரியும் (தகவல்); können = முடியும்.',
    words: [{ de: 'kennen', art: '', en: 'to know (be familiar with)', ta: 'அறிந்திரு', pic: '🤝', ex: 'Ich kenne deinen Bruder.', ex_en: 'I know your brother.' },
      { de: 'wissen', art: '', en: 'to know (a fact)', ta: 'தெரியும்', pic: '💡', ex: 'Ich weiß, wo er wohnt.', ex_en: 'I know where he lives.' },
      { de: 'können', art: '', en: 'can, to be able to', ta: 'முடியும்', pic: '💪', ex: 'Ich kann schwimmen.', ex_en: 'I can swim.' }] },
  { id: 'lernen', type: 'meaning', tip: 'lernen = learn (the student). lehren = teach (the teacher: der Lehrer). In everyday speech "teach" is usually unterrichten or beibringen.',
    tip_ta: 'lernen = கற்றுக்கொள்; lehren = கற்றுக்கொடு.',
    words: [{ de: 'lernen', art: '', en: 'to learn', ta: 'கற்றுக்கொள்', pic: '📚', ex: 'Ich lerne Deutsch.', ex_en: 'I am learning German.' },
      { de: 'lehren', art: '', en: 'to teach', ta: 'கற்றுக்கொடு', pic: '🧑‍🏫', ex: 'Sie lehrt Mathematik an der Uni.', ex_en: 'She teaches maths at the university.' }] },
  { id: 'leihen', type: 'meaning', tip: 'leihen works both ways: jemandem etwas leihen = lend; sich etwas leihen = borrow. ausleihen = borrow (library). mieten = rent (pay money).',
    tip_ta: 'leihen = இரவல் கொடு / வாங்கு; mieten = வாடகைக்கு எடு.',
    words: [{ de: 'leihen', art: '', en: 'to lend / borrow', ta: 'இரவல் கொடு / வாங்கு', pic: '🤲', ex: 'Kannst du mir dein Fahrrad leihen?', ex_en: 'Can you lend me your bike?' },
      { de: 'mieten', art: '', en: 'to rent', ta: 'வாடகைக்கு எடு', pic: '🔑', ex: 'Wir mieten eine Wohnung.', ex_en: 'We are renting a flat.' }] },
  { id: 'spaet', type: 'meaning', tip: 'spät = late (in the day / too late). später = later. zu spät kommen = arrive late. Die Verspätung = delay (trains).',
    tip_ta: 'spät = தாமதம் / இரவு நேரம்; später = பிறகு; Verspätung = தாமதம் (ரயில்).',
    words: [{ de: 'spät', art: '', en: 'late', ta: 'தாமதமாக', pic: '🌙', ex: 'Es ist schon spät.', ex_en: 'It is already late.' },
      { de: 'später', art: '', en: 'later', ta: 'பிறகு', pic: '⏭️', ex: 'Ich rufe dich später an.', ex_en: 'I\'ll call you later.' },
      { de: 'Verspätung', art: 'die', en: 'delay', ta: 'தாமதம்', pic: '🚆', ex: 'Der Zug hat Verspätung.', ex_en: 'The train is delayed.' }] },
  { id: 'fragen', type: 'meaning', tip: 'fragen = ask a question. bitten um = ask for something (a favour). die Frage = question; die Bitte = request.',
    tip_ta: 'fragen = கேள்வி கேள்; bitten = வேண்டு / கோரு.',
    words: [{ de: 'fragen', art: '', en: 'to ask (a question)', ta: 'கேள்வி கேள்', pic: '❓', ex: 'Darf ich dich etwas fragen?', ex_en: 'May I ask you something?' },
      { de: 'bitten', art: '', en: 'to ask for (a favour)', ta: 'வேண்டு', pic: '🙏', ex: 'Ich bitte dich um einen Gefallen.', ex_en: 'I ask you for a favour.' }] },
  { id: 'wohnen', type: 'meaning', tip: 'wohnen = live at an address (Ich wohne in der Hauptstraße). leben = live (be alive / live your life, also: in a country).',
    tip_ta: 'wohnen = வசி (முகவரி); leben = வாழ்.',
    words: [{ de: 'wohnen', art: '', en: 'to live (reside)', ta: 'வசி', pic: '🏠', ex: 'Ich wohne im dritten Stock.', ex_en: 'I live on the third floor.' },
      { de: 'leben', art: '', en: 'to live (be alive)', ta: 'வாழ்', pic: '🌱', ex: 'Meine Oma lebt noch.', ex_en: 'My grandma is still alive.' }] },
  { id: 'stellen', type: 'meaning', tip: 'Movement (Wohin? + Akk.): stellen (upright), legen (flat), setzen (sit), hängen. Position (Wo? + Dat.): stehen, liegen, sitzen, hängen.',
    tip_ta: 'stellen/legen = வை (இயக்கம்); stehen/liegen = இருக்கிறது (நிலை).',
    words: [{ de: 'stellen', art: '', en: 'to put (upright)', ta: 'நிற்கும்படி வை', pic: '🍾', ex: 'Ich stelle die Flasche auf den Tisch.', ex_en: 'I put the bottle on the table.' },
      { de: 'stehen', art: '', en: 'to stand', ta: 'நில்', pic: '🧍', ex: 'Die Flasche steht auf dem Tisch.', ex_en: 'The bottle is (standing) on the table.' },
      { de: 'legen', art: '', en: 'to lay, put (flat)', ta: 'படுக்க வை', pic: '📥', ex: 'Ich lege das Buch auf den Tisch.', ex_en: 'I put the book on the table.' },
      { de: 'liegen', art: '', en: 'to lie', ta: 'கிட', pic: '🛌', ex: 'Das Buch liegt auf dem Tisch.', ex_en: 'The book is (lying) on the table.' }] }
];
