/* Text-Trainer (Task 56): exam-style "translate this English paragraph into German" texts.
   sentence: { en, de, alts (other correct versions), skel (skeleton hint: connectors + verbs, rest …), focus (grammar
   point), ta (Tamil) }. Text 1 = the learner's class/test text (family). Translations and Tamil written with AI
   assistance and reviewed; checked by scripts/check_text_drills.py. */
window.DC_TEXT_DRILLS = [
  { id: 'familie', title: 'Meine Familie', en_title: 'My family', level: 'A2–B1', note: 'Your class text (test topic)',
    sentences: [
      { en: 'I want to talk about my family.', de: 'Ich möchte über meine Familie sprechen.', alts: ['Ich will über meine Familie sprechen.', 'Ich möchte von meiner Familie erzählen.', 'Ich möchte über meine Familie erzählen.'],
        skel: 'Ich möchte … sprechen.', focus: 'Modalverb (pos. 2) + Infinitiv am Ende · über + Akkusativ', ta: 'நான் என் குடும்பத்தைப் பற்றிப் பேச விரும்புகிறேன்.' },
      { en: 'We are five people: my parents, my two siblings, and I.', de: 'Wir sind fünf Personen: meine Eltern, meine zwei Geschwister und ich.', alts: ['Wir sind fünf Leute: meine Eltern, meine zwei Geschwister und ich.', 'Wir sind zu fünft: meine Eltern, meine zwei Geschwister und ich.'],
        skel: 'Wir sind …: meine Eltern, meine … Geschwister und ich.', focus: 'Geschwister = siblings (always plural) · no comma before "und"', ta: 'நாங்கள் ஐந்து பேர்: என் பெற்றோர், என் இரண்டு உடன்பிறப்புகள், நான்.' },
      { en: 'When I was little, we had a small house in the countryside.', de: 'Als ich klein war, hatten wir ein kleines Haus auf dem Land.', alts: ['Als ich klein war, hatten wir ein kleines Haus auf dem Dorf.'],
        skel: 'Als ich … war, hatten wir … auf dem Land.', focus: 'als = once in the past (not wenn) · Nebensatz first → verb right after the comma · hatten (Präteritum) · auf dem Land = in the countryside', ta: 'நான் சிறுவனாக இருந்தபோது, எங்களுக்குக் கிராமத்தில் ஒரு சிறிய வீடு இருந்தது.' },
      { en: 'I had to take the bus to school every day, and my sister always wanted to sit next to me.', de: 'Ich musste jeden Tag mit dem Bus zur Schule fahren, und meine Schwester wollte immer neben mir sitzen.', alts: ['Ich musste jeden Tag mit dem Bus zur Schule fahren und meine Schwester wollte immer neben mir sitzen.', 'Ich musste jeden Tag den Bus zur Schule nehmen, und meine Schwester wollte immer neben mir sitzen.'],
        skel: 'Ich musste … mit dem Bus zur Schule fahren, und meine Schwester wollte … neben mir sitzen.', focus: 'musste / wollte (modal Präteritum) + Infinitiv am Ende · mit dem Bus fahren · neben + Dativ (mir)', ta: 'நான் தினமும் பேருந்தில் பள்ளிக்குப் போக வேண்டியிருந்தது, என் சகோதரி எப்போதும் என் அருகில் உட்கார விரும்பினாள்.' },
      { en: 'On weekends, we often went for walks and played in the garden.', de: 'Am Wochenende sind wir oft spazieren gegangen und haben im Garten gespielt.', alts: ['Am Wochenende gingen wir oft spazieren und spielten im Garten.', 'An den Wochenenden sind wir oft spazieren gegangen und haben im Garten gespielt.', 'An den Wochenenden gingen wir oft spazieren und spielten im Garten.'],
        skel: 'Am Wochenende sind wir … spazieren gegangen und haben … gespielt.', focus: 'Time first → verb pos. 2 · spazieren gehen (sein!) · Perfekt (spoken) or Präteritum (written) — both correct', ta: 'வார இறுதிகளில் நாங்கள் அடிக்கடி நடக்கச் சென்றோம், தோட்டத்தில் விளையாடினோம்.' },
      { en: 'Because my family is very important to me, I try to talk to them every day.', de: 'Weil meine Familie mir sehr wichtig ist, versuche ich, jeden Tag mit ihnen zu sprechen.', alts: ['Weil meine Familie für mich sehr wichtig ist, versuche ich, jeden Tag mit ihnen zu sprechen.', 'Da meine Familie mir sehr wichtig ist, versuche ich, jeden Tag mit ihnen zu sprechen.', 'Weil mir meine Familie sehr wichtig ist, versuche ich, jeden Tag mit ihnen zu sprechen.'],
        skel: 'Weil meine Familie … wichtig ist, versuche ich, … mit ihnen zu sprechen.', focus: 'weil → verb at the end (ist) · then verb + subject (versuche ich) · zu + Infinitiv at the very end · "jeden Tag" = two words', ta: 'என் குடும்பம் எனக்கு மிகவும் முக்கியம் என்பதால், நான் தினமும் அவர்களுடன் பேச முயற்சிக்கிறேன்.' },
      { en: 'When I have time, I call my mother.', de: 'Wenn ich Zeit habe, rufe ich meine Mutter an.', alts: [],
        skel: 'Wenn ich Zeit habe, rufe ich … an.', focus: 'wenn = when/whenever (present) · anrufen: "an" goes to the end', ta: 'எனக்கு நேரம் இருக்கும்போது, நான் என் அம்மாவை அழைக்கிறேன்.' },
      { en: 'I know that she is always happy.', de: 'Ich weiß, dass sie immer glücklich ist.', alts: ['Ich weiß, dass sie sich immer freut.'],
        skel: 'Ich weiß, dass sie … ist.', focus: 'dass → verb at the end · comma before dass · wissen: ich weiß', ta: 'அவள் எப்போதும் மகிழ்ச்சியாக இருக்கிறாள் என்று எனக்குத் தெரியும்.' },
      { en: 'Although we no longer live together, we visit each other often.', de: 'Obwohl wir nicht mehr zusammen wohnen, besuchen wir uns oft.', alts: ['Obwohl wir nicht mehr zusammenwohnen, besuchen wir uns oft.', 'Obwohl wir nicht mehr zusammen leben, besuchen wir uns oft.', 'Obwohl wir nicht mehr zusammen wohnen, besuchen wir einander oft.', 'Obwohl wir nicht mehr zusammen wohnen, besuchen wir uns häufig.'],
        skel: 'Obwohl wir nicht mehr … wohnen, besuchen wir uns ….', focus: 'obwohl → verb at the end · no longer = nicht mehr · each other = uns', ta: 'நாங்கள் இப்போது ஒன்றாக வசிக்காவிட்டாலும், அடிக்கடி ஒருவரையொருவர் சந்திக்கிறோம்.' },
      { en: 'Therefore, our family is still very close.', de: 'Deshalb ist unsere Familie immer noch sehr eng verbunden.', alts: ['Deshalb ist unsere Familie noch immer sehr eng verbunden.', 'Darum ist unsere Familie immer noch sehr eng verbunden.', 'Deshalb hält unsere Familie immer noch fest zusammen.', 'Deshalb ist unsere Familie immer noch sehr eng.'],
        skel: 'Deshalb ist unsere Familie … verbunden.', focus: 'deshalb (pos. 1) → verb immediately (ist) · still = immer noch · close (family) = eng verbunden', ta: 'அதனால் எங்கள் குடும்பம் இன்னும் மிகவும் நெருக்கமாக இருக்கிறது.' },
      { en: 'Nevertheless, I wish that we could spend more time together.', de: 'Trotzdem wünsche ich mir, dass wir mehr Zeit zusammen verbringen könnten.', alts: ['Trotzdem wünsche ich mir, dass wir mehr Zeit miteinander verbringen könnten.', 'Trotzdem wünsche ich mir, dass wir mehr Zeit zusammen verbringen können.', 'Trotzdem würde ich gern mehr Zeit mit ihnen verbringen.'],
        skel: 'Trotzdem wünsche ich mir, dass wir … verbringen könnten.', focus: 'trotzdem → verb immediately · sich etwas wünschen (mir) · dass → könnten (Konjunktiv II) at the end · spend time = Zeit verbringen', ta: 'இருந்தாலும், நாங்கள் இன்னும் அதிக நேரம் ஒன்றாகச் செலவிட முடிந்தால் நன்றாக இருக்கும் என்று விரும்புகிறேன்.' },
      { en: 'Can you tell me about your family?', de: 'Kannst du mir von deiner Familie erzählen?', alts: ['Kannst du mir etwas über deine Familie erzählen?', 'Können Sie mir von Ihrer Familie erzählen?', 'Kannst du mir über deine Familie erzählen?'],
        skel: 'Kannst du mir von … erzählen?', focus: 'Ja/Nein-question: verb first · erzählen von + Dativ (deiner Familie) · mir (Dativ)', ta: 'உன் குடும்பத்தைப் பற்றி எனக்குச் சொல்ல முடியுமா?' },
      { en: 'I would also like to know if you have siblings.', de: 'Ich möchte auch wissen, ob du Geschwister hast.', alts: ['Ich würde auch gern wissen, ob du Geschwister hast.', 'Ich würde auch gerne wissen, ob du Geschwister hast.', 'Ich möchte auch gern wissen, ob du Geschwister hast.'],
        skel: 'Ich möchte auch wissen, ob du … hast.', focus: 'if = whether → ob (NOT wenn) · ob → verb at the end (hast)', ta: 'உனக்கு உடன்பிறப்புகள் இருக்கிறார்களா என்றும் தெரிந்துகொள்ள விரும்புகிறேன்.' },
      { en: 'I help my parents to thank them.', de: 'Ich helfe meinen Eltern, um ihnen zu danken.', alts: ['Ich helfe meinen Eltern, um mich bei ihnen zu bedanken.'],
        skel: 'Ich helfe meinen Eltern, um ihnen zu danken.', focus: 'helfen + Dativ (meinen Eltern) · danken + Dativ (ihnen) · um … zu = in order to', ta: 'அவர்களுக்கு நன்றி சொல்வதற்காக நான் என் பெற்றோருக்கு உதவுகிறேன்.' },
      { en: 'I love my family very much.', de: 'Ich liebe meine Familie sehr.', alts: ['Ich liebe meine Familie sehr, sehr.'],
        skel: 'Ich liebe … sehr.', focus: '"very much" = sehr (at the end) — not "viel"', ta: 'நான் என் குடும்பத்தை மிகவும் நேசிக்கிறேன்.' }] },
  { id: 'freunde', title: 'Meine beste Freundin', en_title: 'My best friend', level: 'A2–B1', note: 'Same grammar, new topic',
    sentences: [
      { en: 'I would like to tell you about my best friend.', de: 'Ich möchte dir von meiner besten Freundin erzählen.', alts: ['Ich möchte dir über meine beste Freundin erzählen.', 'Ich möchte euch von meiner besten Freundin erzählen.'],
        skel: 'Ich möchte dir von meiner … erzählen.', focus: 'erzählen von + Dativ → meiner besten Freundin (adjective -en)', ta: 'என் நெருங்கிய தோழியைப் பற்றி உனக்குச் சொல்ல விரும்புகிறேன்.' },
      { en: 'Her name is Meena and she lives in Chennai.', de: 'Sie heißt Meena und wohnt in Chennai.', alts: ['Sie heißt Meena und sie wohnt in Chennai.', 'Ihr Name ist Meena und sie wohnt in Chennai.', 'Sie heißt Meena und lebt in Chennai.'],
        skel: 'Sie heißt … und wohnt in ….', focus: 'Her name is = Sie heißt · und + verb (same subject)', ta: 'அவள் பெயர் மீனா, அவள் சென்னையில் வசிக்கிறாள்.' },
      { en: 'When we were children, we went to the same school.', de: 'Als wir Kinder waren, gingen wir in dieselbe Schule.', alts: ['Als wir Kinder waren, sind wir in dieselbe Schule gegangen.', 'Als wir Kinder waren, gingen wir auf dieselbe Schule.', 'Als wir Kinder waren, sind wir auf dieselbe Schule gegangen.', 'Als wir Kinder waren, gingen wir in die gleiche Schule.'],
        skel: 'Als wir Kinder waren, gingen wir in dieselbe ….', focus: 'als + Präteritum · verb right after the comma', ta: 'நாங்கள் குழந்தைகளாக இருந்தபோது, ஒரே பள்ளிக்குச் சென்றோம்.' },
      { en: 'We had to do our homework together every day.', de: 'Wir mussten jeden Tag zusammen unsere Hausaufgaben machen.', alts: ['Wir mussten unsere Hausaufgaben jeden Tag zusammen machen.', 'Wir mussten jeden Tag gemeinsam unsere Hausaufgaben machen.'],
        skel: 'Wir mussten … Hausaufgaben machen.', focus: 'mussten (modal Präteritum) + Infinitiv am Ende · Hausaufgaben machen', ta: 'நாங்கள் தினமும் ஒன்றாக வீட்டுப்பாடம் செய்ய வேண்டியிருந்தது.' },
      { en: 'Because she is very funny, I always laugh a lot with her.', de: 'Weil sie sehr lustig ist, lache ich immer viel mit ihr.', alts: ['Da sie sehr lustig ist, lache ich immer viel mit ihr.', 'Weil sie sehr witzig ist, lache ich immer viel mit ihr.'],
        skel: 'Weil sie … ist, lache ich … mit ihr.', focus: 'weil → verb end · verb + subject after the comma · mit + Dativ (ihr)', ta: 'அவள் மிகவும் வேடிக்கையானவள் என்பதால், நான் அவளுடன் எப்போதும் நிறைய சிரிக்கிறேன்.' },
      { en: 'Although she lives far away, we talk on the phone every week.', de: 'Obwohl sie weit weg wohnt, telefonieren wir jede Woche.', alts: ['Obwohl sie weit weg wohnt, telefonieren wir jede Woche miteinander.', 'Obwohl sie weit entfernt wohnt, telefonieren wir jede Woche.'],
        skel: 'Obwohl sie weit weg wohnt, telefonieren wir ….', focus: 'obwohl → verb end · talk on the phone = telefonieren', ta: 'அவள் தொலைவில் வசித்தாலும், நாங்கள் ஒவ்வொரு வாரமும் தொலைபேசியில் பேசுகிறோம்.' },
      { en: 'I know that she will always help me.', de: 'Ich weiß, dass sie mir immer helfen wird.', alts: [],
        skel: 'Ich weiß, dass sie mir … helfen wird.', focus: 'dass → wird at the very end · helfen + Dativ (mir) · Futur: werden + Infinitiv', ta: 'அவள் எப்போதும் எனக்கு உதவுவாள் என்று எனக்குத் தெரியும்.' },
      { en: 'Therefore, our friendship is very important to me.', de: 'Deshalb ist mir unsere Freundschaft sehr wichtig.', alts: ['Deshalb ist unsere Freundschaft für mich sehr wichtig.', 'Deshalb ist unsere Freundschaft mir sehr wichtig.', 'Darum ist mir unsere Freundschaft sehr wichtig.'],
        skel: 'Deshalb ist … sehr wichtig.', focus: 'deshalb → verb immediately', ta: 'அதனால் எங்கள் நட்பு எனக்கு மிகவும் முக்கியம்.' },
      { en: 'Nevertheless, I wish that we could see each other more often.', de: 'Trotzdem wünsche ich mir, dass wir uns öfter sehen könnten.', alts: ['Trotzdem wünsche ich mir, dass wir uns öfter sehen können.', 'Trotzdem wünsche ich mir, dass wir uns häufiger sehen könnten.'],
        skel: 'Trotzdem wünsche ich mir, dass wir uns … sehen könnten.', focus: 'trotzdem → verb immediately · dass → könnten at the end · each other = uns', ta: 'இருந்தாலும், நாங்கள் இன்னும் அடிக்கடி சந்திக்க முடிந்தால் நன்றாக இருக்கும் என்று விரும்புகிறேன்.' },
      { en: 'Do you also have a best friend?', de: 'Hast du auch eine beste Freundin oder einen besten Freund?', alts: ['Hast du auch einen besten Freund?', 'Hast du auch eine beste Freundin?', 'Hast du auch einen besten Freund oder eine beste Freundin?'],
        skel: 'Hast du auch einen besten Freund?', focus: 'question: verb first · Akkusativ: einen besten Freund', ta: 'உனக்கும் ஒரு நெருங்கிய நண்பன் / தோழி இருக்கிறார்களா?' },
      { en: 'I would like to know if you meet often.', de: 'Ich möchte wissen, ob ihr euch oft trefft.', alts: ['Ich würde gern wissen, ob ihr euch oft trefft.', 'Ich würde gerne wissen, ob ihr euch oft trefft.'],
        skel: 'Ich möchte wissen, ob ihr euch … trefft.', focus: 'ob → verb end · sich treffen (ihr → euch … trefft)', ta: 'நீங்கள் அடிக்கடி சந்திக்கிறீர்களா என்று தெரிந்துகொள்ள விரும்புகிறேன்.' }] },
  { id: 'wohnung', title: 'Meine Wohnung', en_title: 'My flat', level: 'A2–B1', note: 'Same grammar, new topic',
    sentences: [
      { en: 'Today I want to write about my flat.', de: 'Heute möchte ich über meine Wohnung schreiben.', alts: ['Heute will ich über meine Wohnung schreiben.'],
        skel: 'Heute möchte ich über … schreiben.', focus: 'Heute (pos. 1) → verb → subject', ta: 'இன்று என் வீட்டைப் பற்றி எழுத விரும்புகிறேன்.' },
      { en: 'I live with my husband in a flat in Stuttgart.', de: 'Ich wohne mit meinem Mann in einer Wohnung in Stuttgart.', alts: ['Ich wohne mit meinem Mann in Stuttgart in einer Wohnung.'],
        skel: 'Ich wohne mit meinem Mann in einer ….', focus: 'mit + Dativ (meinem Mann) · in + Dativ (Wo?): in einer Wohnung', ta: 'நான் என் கணவருடன் ஸ்டுட்கார்ட்டில் ஒரு வீட்டில் வசிக்கிறேன்.' },
      { en: 'When we came to Germany, we had only one small room.', de: 'Als wir nach Deutschland kamen, hatten wir nur ein kleines Zimmer.', alts: ['Als wir nach Deutschland gekommen sind, hatten wir nur ein kleines Zimmer.'],
        skel: 'Als wir nach Deutschland kamen, hatten wir nur ….', focus: 'als + Präteritum · nach + country · hatten', ta: 'நாங்கள் ஜெர்மனிக்கு வந்தபோது, எங்களிடம் ஒரே ஒரு சிறிய அறை மட்டுமே இருந்தது.' },
      { en: 'We had to look for a new flat for a long time.', de: 'Wir mussten lange eine neue Wohnung suchen.', alts: ['Wir mussten lange nach einer neuen Wohnung suchen.'],
        skel: 'Wir mussten lange … suchen.', focus: 'mussten + Infinitiv am Ende · for a long time = lange', ta: 'நாங்கள் நீண்ட காலம் புதிய வீடு தேட வேண்டியிருந்தது.' },
      { en: 'Now we have three rooms, a kitchen and a balcony.', de: 'Jetzt haben wir drei Zimmer, eine Küche und einen Balkon.', alts: [],
        skel: 'Jetzt haben wir …, eine Küche und einen Balkon.', focus: 'haben + Akkusativ: einen Balkon · die Küche (not der Kuchen!)', ta: 'இப்போது எங்களிடம் மூன்று அறைகள், ஒரு சமையலறை, ஒரு பால்கனி இருக்கின்றன.' },
      { en: 'Because the flat is near the station, I can walk to work.', de: 'Weil die Wohnung in der Nähe vom Bahnhof ist, kann ich zu Fuß zur Arbeit gehen.', alts: ['Weil die Wohnung in der Nähe des Bahnhofs ist, kann ich zu Fuß zur Arbeit gehen.', 'Da die Wohnung in der Nähe vom Bahnhof ist, kann ich zu Fuß zur Arbeit gehen.', 'Weil die Wohnung nah am Bahnhof ist, kann ich zu Fuß zur Arbeit gehen.'],
        skel: 'Weil die Wohnung in der Nähe … ist, kann ich zu Fuß zur Arbeit gehen.', focus: 'weil → verb end · kann ich … gehen · zu Fuß = on foot', ta: 'வீடு ரயில் நிலையத்துக்கு அருகில் இருப்பதால், நான் நடந்தே வேலைக்குப் போக முடியும்.' },
      { en: 'Although the rent is high, we are happy here.', de: 'Obwohl die Miete hoch ist, sind wir hier glücklich.', alts: ['Obwohl die Miete teuer ist, sind wir hier glücklich.', 'Obwohl die Miete hoch ist, sind wir hier zufrieden.'],
        skel: 'Obwohl die Miete … ist, sind wir hier ….', focus: 'obwohl → verb end · sind wir (verb right after the comma)', ta: 'வாடகை அதிகமாக இருந்தாலும், நாங்கள் இங்கே மகிழ்ச்சியாக இருக்கிறோம்.' },
      { en: 'Our neighbours are very friendly, therefore we often invite them.', de: 'Unsere Nachbarn sind sehr freundlich, deshalb laden wir sie oft ein.', alts: ['Unsere Nachbarn sind sehr nett, deshalb laden wir sie oft ein.', 'Unsere Nachbarn sind sehr freundlich, darum laden wir sie oft ein.'],
        skel: 'Unsere Nachbarn sind …, deshalb laden wir sie … ein.', focus: 'deshalb → verb immediately · einladen: "ein" at the end', ta: 'எங்கள் அண்டை வீட்டார் மிகவும் அன்பானவர்கள், அதனால் நாங்கள் அவர்களை அடிக்கடி அழைக்கிறோம்.' },
      { en: 'Nevertheless, I wish that we had a garden.', de: 'Trotzdem wünsche ich mir, dass wir einen Garten hätten.', alts: ['Trotzdem wünsche ich mir einen Garten.', 'Trotzdem hätte ich gern einen Garten.'],
        skel: 'Trotzdem wünsche ich mir, dass wir einen Garten hätten.', focus: 'trotzdem → verb immediately · dass → hätten (Konjunktiv II) at the end', ta: 'இருந்தாலும், எங்களுக்கு ஒரு தோட்டம் இருந்தால் நன்றாக இருக்கும் என்று விரும்புகிறேன்.' },
      { en: 'How big is your flat?', de: 'Wie groß ist deine Wohnung?', alts: ['Wie groß ist Ihre Wohnung?'],
        skel: 'Wie groß ist …?', focus: 'W-question: W-word + verb', ta: 'உன் வீடு எவ்வளவு பெரியது?' },
      { en: 'I would like to know if you live in the city or in the countryside.', de: 'Ich möchte wissen, ob du in der Stadt oder auf dem Land wohnst.', alts: ['Ich würde gern wissen, ob du in der Stadt oder auf dem Land wohnst.', 'Ich würde gerne wissen, ob du in der Stadt oder auf dem Land wohnst.'],
        skel: 'Ich möchte wissen, ob du in der Stadt oder auf dem Land wohnst.', focus: 'ob → verb end · auf dem Land = in the countryside', ta: 'நீ நகரத்தில் வசிக்கிறாயா கிராமத்தில் வசிக்கிறாயா என்று தெரிந்துகொள்ள விரும்புகிறேன்.' }] },
  { id: 'alltag', title: 'Mein Alltag', en_title: 'My daily life', level: 'A2–B1', note: 'Same grammar, new topic',
    sentences: [
      { en: 'I would like to describe my daily life.', de: 'Ich möchte meinen Alltag beschreiben.', alts: ['Ich will meinen Alltag beschreiben.'],
        skel: 'Ich möchte meinen … beschreiben.', focus: 'der Alltag → Akkusativ meinen Alltag', ta: 'என் அன்றாட வாழ்க்கையை விவரிக்க விரும்புகிறேன்.' },
      { en: 'I get up at six o\'clock every morning.', de: 'Ich stehe jeden Morgen um sechs Uhr auf.', alts: ['Jeden Morgen stehe ich um sechs Uhr auf.', 'Ich stehe jeden Morgen um 6 Uhr auf.'],
        skel: 'Ich stehe … um sechs Uhr auf.', focus: 'aufstehen: "auf" at the end · um + time', ta: 'நான் தினமும் காலை ஆறு மணிக்கு எழுகிறேன்.' },
      { en: 'Before I go to work, I drink a cup of tea.', de: 'Bevor ich zur Arbeit gehe, trinke ich eine Tasse Tee.', alts: ['Bevor ich zur Arbeit fahre, trinke ich eine Tasse Tee.'],
        skel: 'Bevor ich zur Arbeit gehe, trinke ich ….', focus: 'bevor → verb end · verb + subject after the comma', ta: 'வேலைக்குப் போவதற்கு முன், நான் ஒரு கோப்பை தேநீர் குடிக்கிறேன்.' },
      { en: 'Last year I had to work on Saturdays too.', de: 'Letztes Jahr musste ich auch samstags arbeiten.', alts: ['Letztes Jahr musste ich auch am Samstag arbeiten.', 'Im letzten Jahr musste ich auch samstags arbeiten.'],
        skel: 'Letztes Jahr musste ich auch … arbeiten.', focus: 'time first → musste ich · modal Präteritum', ta: 'போன வருடம் நான் சனிக்கிழமைகளிலும் வேலை செய்ய வேண்டியிருந்தது.' },
      { en: 'When I come home, I cook dinner for my family.', de: 'Wenn ich nach Hause komme, koche ich das Abendessen für meine Familie.', alts: ['Wenn ich nach Hause komme, koche ich Abendessen für meine Familie.'],
        skel: 'Wenn ich nach Hause komme, koche ich … für meine Familie.', focus: 'wenn (every time, present) · nach Hause (going home)', ta: 'நான் வீட்டுக்கு வரும்போது, என் குடும்பத்துக்காக இரவு உணவு சமைக்கிறேன்.' },
      { en: 'Because I am often tired, I go to bed early.', de: 'Weil ich oft müde bin, gehe ich früh ins Bett.', alts: ['Da ich oft müde bin, gehe ich früh ins Bett.', 'Weil ich oft müde bin, gehe ich früh schlafen.'],
        skel: 'Weil ich oft müde bin, gehe ich früh ins Bett.', focus: 'weil → bin at the end · ins Bett (Wohin → Akkusativ)', ta: 'நான் அடிக்கடி களைப்பாக இருப்பதால், சீக்கிரம் தூங்கப் போகிறேன்.' },
      { en: 'Although I have little time, I learn German every day.', de: 'Obwohl ich wenig Zeit habe, lerne ich jeden Tag Deutsch.', alts: ['Obwohl ich wenig Zeit habe, lerne ich täglich Deutsch.'],
        skel: 'Obwohl ich wenig Zeit habe, lerne ich … Deutsch.', focus: 'obwohl → verb end', ta: 'எனக்குக் குறைவான நேரம் இருந்தாலும், நான் தினமும் ஜெர்மன் கற்கிறேன்.' },
      { en: 'I know that practice is important.', de: 'Ich weiß, dass Übung wichtig ist.', alts: ['Ich weiß, dass Üben wichtig ist.', 'Ich weiß, dass das Üben wichtig ist.'],
        skel: 'Ich weiß, dass … wichtig ist.', focus: 'dass → ist at the end', ta: 'பயிற்சி முக்கியம் என்று எனக்குத் தெரியும்.' },
      { en: 'Therefore I try to speak German with my colleagues.', de: 'Deshalb versuche ich, mit meinen Kollegen Deutsch zu sprechen.', alts: ['Deshalb versuche ich, Deutsch mit meinen Kollegen zu sprechen.', 'Darum versuche ich, mit meinen Kollegen Deutsch zu sprechen.'],
        skel: 'Deshalb versuche ich, mit meinen Kollegen Deutsch zu sprechen.', focus: 'deshalb → verb immediately · zu + Infinitiv at the end · mit + Dativ plural (meinen Kollegen)', ta: 'அதனால் நான் என் சக ஊழியர்களுடன் ஜெர்மனில் பேச முயற்சிக்கிறேன்.' },
      { en: 'Nevertheless, I would like to have more free time.', de: 'Trotzdem hätte ich gern mehr Freizeit.', alts: ['Trotzdem hätte ich gerne mehr Freizeit.', 'Trotzdem würde ich gern mehr Freizeit haben.', 'Trotzdem möchte ich mehr Freizeit haben.'],
        skel: 'Trotzdem hätte ich gern mehr Freizeit.', focus: 'trotzdem → verb immediately · ich hätte gern = I would like', ta: 'இருந்தாலும், எனக்கு இன்னும் அதிக ஓய்வு நேரம் இருந்தால் நன்றாக இருக்கும்.' },
      { en: 'What do you do after work?', de: 'Was machst du nach der Arbeit?', alts: ['Was machen Sie nach der Arbeit?'],
        skel: 'Was machst du nach der Arbeit?', focus: 'W-question · nach + Dativ (nach der Arbeit)', ta: 'வேலைக்குப் பிறகு நீ என்ன செய்கிறாய்?' }] }
];

/* ⚡ Crashkurs (for the test): quick checks on connectors, A1 word order and Akkusativ/Dativ.
   quiz: { a: 'kon'|'satz'|'kasus', p: prompt ("___" = gap; no gap = pick the correct sentence), o: [correct, wrong…], exp }
   join: two sentences + a connector → one sentence; de = model, alts = other correct versions. */
window.DC_CRASH = {
  quiz: [
    { a: 'kon', p: 'Ich bleibe zu Hause, weil …', o: ['Ich bleibe zu Hause, weil ich krank bin.', 'Ich bleibe zu Hause, weil ich bin krank.', 'Ich bleibe zu Hause, weil bin ich krank.'], exp: 'weil → the verb goes to the END (… krank bin).' },
    { a: 'kon', p: 'Ich bin krank, deshalb …', o: ['Ich bin krank, deshalb bleibe ich zu Hause.', 'Ich bin krank, deshalb ich bleibe zu Hause.', 'Ich bin krank, deshalb ich zu Hause bleibe.'], exp: 'deshalb takes position 1 → the verb comes IMMEDIATELY after it (bleibe ich).' },
    { a: 'kon', p: 'Ich bleibe zu Hause, denn …', o: ['Ich bleibe zu Hause, denn ich bin krank.', 'Ich bleibe zu Hause, denn bin ich krank.', 'Ich bleibe zu Hause, denn ich krank bin.'], exp: 'denn = position 0 (like und/aber/oder) → normal order: ich bin.' },
    { a: 'kon', p: 'Obwohl es regnet, …', o: ['Obwohl es regnet, gehe ich spazieren.', 'Obwohl es regnet, ich gehe spazieren.', 'Obwohl regnet es, gehe ich spazieren.'], exp: 'obwohl → verb at the end (regnet). The whole clause is position 1 → then the verb (gehe) and the subject (ich).' },
    { a: 'kon', p: 'Es regnet, trotzdem …', o: ['Es regnet, trotzdem gehe ich spazieren.', 'Es regnet, trotzdem ich gehe spazieren.', 'Es regnet, trotzdem ich spazieren gehe.'], exp: 'trotzdem (nevertheless) = position 1 → verb immediately: trotzdem gehe ich.' },
    { a: 'kon', p: 'Ich glaube, dass …', o: ['Ich glaube, dass er morgen kommt.', 'Ich glaube, dass er kommt morgen.', 'Ich glaube, dass kommt er morgen.'], exp: 'dass → verb at the end (kommt).' },
    { a: 'kon', p: 'I don\'t know whether she has time.', o: ['Ich weiß nicht, ob sie Zeit hat.', 'Ich weiß nicht, ob hat sie Zeit.', 'Ich weiß nicht, wenn sie Zeit hat.'], exp: 'whether / if (yes-no question) = ob, not wenn · verb at the end.' },
    { a: 'kon', p: 'When I was a child, I lived in Chennai.', o: ['Als ich ein Kind war, wohnte ich in Chennai.', 'Wenn ich ein Kind war, wohnte ich in Chennai.', 'Als ich war ein Kind, wohnte ich in Chennai.'], exp: 'one time in the past = als (not wenn) · verb at the end of the als-clause.' },
    { a: 'kon', p: 'When I have time, I cook.', o: ['Wenn ich Zeit habe, koche ich.', 'Wenn ich Zeit habe, ich koche.', 'Als ich Zeit habe, koche ich.'], exp: 'present / every time = wenn · after the clause comes the verb: koche ich.' },
    { a: 'kon', p: 'Ich bin müde, aber …', o: ['Ich bin müde, aber ich arbeite noch.', 'Ich bin müde, aber arbeite ich noch.', 'Ich bin müde, aber ich noch arbeite.'], exp: 'aber = position 0 → normal order (ich arbeite).' },
    { a: 'kon', p: 'Ich trinke keinen Kaffee, ___ Tee.', o: ['sondern', 'aber', 'oder'], exp: 'not A but B (after kein/nicht) = sondern.' },
    { a: 'kon', p: 'I learn German in order to work in Germany.', o: ['Ich lerne Deutsch, um in Deutschland zu arbeiten.', 'Ich lerne Deutsch, um zu arbeiten in Deutschland.', 'Ich lerne Deutsch, für in Deutschland zu arbeiten.'], exp: 'in order to = um … zu + infinitive at the very end.' },
    { a: 'kon', p: 'I try to speak German every day.', o: ['Ich versuche, jeden Tag Deutsch zu sprechen.', 'Ich versuche, jeden Tag zu Deutsch sprechen.', 'Ich versuche, zu sprechen jeden Tag Deutsch.'], exp: 'versuchen + zu + infinitive — "zu sprechen" is the last thing in the sentence.' },
    { a: 'kon', p: 'Weil ich müde bin, …', o: ['Weil ich müde bin, gehe ich schlafen.', 'Weil ich müde bin, ich gehe schlafen.', 'Weil ich bin müde, gehe ich schlafen.'], exp: 'weil-clause first → "verb, verb" in the middle: … bin, gehe ich …' },
    { a: 'kon', p: 'Ich hoffe, dass …', o: ['Ich hoffe, dass ich morgen kommen kann.', 'Ich hoffe, dass ich kann morgen kommen.', 'Ich hoffe, dass ich morgen kann kommen.'], exp: 'modal verb in a dass-clause: infinitive + modal at the very end (kommen kann).' },
    { a: 'kon', p: 'Ich bin müde, weil …', o: ['Ich bin müde, weil ich früh aufstehe.', 'Ich bin müde, weil ich stehe früh auf.', 'Ich bin müde, weil ich früh auf stehe.'], exp: 'separable verb at the end of a weil-clause is written as ONE word: aufstehe.' },
    { a: 'kon', p: 'Ich bin müde, weil …', o: ['Ich bin müde, weil ich schlecht geschlafen habe.', 'Ich bin müde, weil ich habe schlecht geschlafen.', 'Ich bin müde, weil ich schlecht habe geschlafen.'], exp: 'Perfekt in a weil-clause: Partizip + haben/sein at the end (geschlafen habe).' },
    { a: 'kon', p: 'Zuerst frühstücke ich, dann …', o: ['Zuerst frühstücke ich, dann gehe ich zur Arbeit.', 'Zuerst frühstücke ich, dann ich gehe zur Arbeit.', 'Zuerst frühstücke ich, dann ich zur Arbeit gehe.'], exp: 'dann / danach / zuerst = position 1 → verb immediately.' },
    { a: 'satz', p: 'Today I am going to the cinema.', o: ['Heute gehe ich ins Kino.', 'Heute ich gehe ins Kino.', 'Heute ich ins Kino gehe.'], exp: 'Verb is ALWAYS position 2. Time first → verb → subject.' },
    { a: 'satz', p: 'I can cook well.', o: ['Ich kann gut kochen.', 'Ich kann kochen gut.', 'Ich gut kann kochen.'], exp: 'Modal verb pos. 2, infinitive at the END (Satzklammer).' },
    { a: 'satz', p: 'I get up at 7 o\'clock.', o: ['Ich stehe um 7 Uhr auf.', 'Ich aufstehe um 7 Uhr.', 'Ich um 7 Uhr aufstehe.'], exp: 'Separable verb: stehe (pos. 2) … auf (end).' },
    { a: 'satz', p: 'I ate pizza yesterday.', o: ['Ich habe gestern Pizza gegessen.', 'Ich habe gegessen gestern Pizza.', 'Ich gestern habe Pizza gegessen.'], exp: 'Perfekt: haben (pos. 2) … Partizip (end).' },
    { a: 'satz', p: 'Where do you live?', o: ['Wo wohnst du?', 'Wo du wohnst?', 'Wohnst wo du?'], exp: 'W-question: W-word → verb → subject.' },
    { a: 'satz', p: 'Do you have time?', o: ['Hast du Zeit?', 'Hast Zeit du?', 'Du Zeit hast?'], exp: 'Yes/no question: verb FIRST.' },
    { a: 'satz', p: 'I don\'t have a car.', o: ['Ich habe kein Auto.', 'Ich habe nicht ein Auto.', 'Ich habe nicht Auto.'], exp: 'not a / no + noun = kein (keine, keinen …).' },
    { a: 'satz', p: 'I don\'t sleep well.', o: ['Ich schlafe nicht gut.', 'Ich schlafe gut nicht.', 'Ich nicht schlafe gut.'], exp: 'nicht stands before the word it negates (gut).' },
    { a: 'satz', p: 'I went to Chennai.', o: ['Ich bin nach Chennai gefahren.', 'Ich habe nach Chennai gefahren.', 'Ich bin nach Chennai gefahrt.'], exp: 'movement (fahren, gehen, fliegen, kommen) → Perfekt with SEIN · gefahren.' },
    { a: 'satz', p: 'Du ___ gut Deutsch. (sprechen)', o: ['sprichst', 'sprechst', 'spricht'], exp: 'e → i verbs change in du/er: du sprichst, er spricht.' },
    { a: 'satz', p: 'Mein Bruder ___ in Berlin. (arbeiten)', o: ['arbeitet', 'arbeit', 'arbeiten'], exp: 'er/sie/es → -t; stem ends in -t → -et: arbeitet.' },
    { a: 'satz', p: 'I will go to Chennai next week.', o: ['Ich werde nächste Woche nach Chennai fahren.', 'Ich werde fahren nächste Woche nach Chennai.', 'Ich fahre werde nächste Woche nach Chennai.'], exp: 'Futur: werden (pos. 2) … infinitive at the end. (Also OK: Ich fahre nächste Woche nach Chennai.)' },
    { a: 'satz', p: 'I am going to Berlin by train tomorrow.', o: ['Ich fahre morgen mit dem Zug nach Berlin.', 'Ich fahre nach Berlin morgen mit dem Zug.', 'Ich fahre mit dem Zug nach Berlin morgen.'], exp: 'Middle order = Te-Ka-Mo-Lo: time (morgen) → manner (mit dem Zug) → place (nach Berlin).' },
    { a: 'satz', p: 'How old are you?', o: ['Wie alt bist du?', 'Wie alt du bist?', 'Wie bist du alt?'], exp: '"Wie alt" is one question word → verb → subject.' },
    { a: 'satz', p: 'I would like to drink a coffee.', o: ['Ich möchte einen Kaffee trinken.', 'Ich möchte trinken einen Kaffee.', 'Ich möchte einen Kaffee trinke.'], exp: 'möchte (pos. 2) + infinitive (trinken) at the end · der Kaffee → einen (Akk).' },
    { a: 'kasus', p: 'Ich habe ___ Bruder.', o: ['einen', 'ein', 'einem'], exp: 'haben + Akkusativ · der Bruder → einen Bruder.' },
    { a: 'kasus', p: 'Ich fahre mit ___ Bus.', o: ['dem', 'den', 'der'], exp: 'mit + Dativ · der Bus → dem Bus.' },
    { a: 'kasus', p: 'Ich helfe ___ Mutter.', o: ['meiner', 'meine', 'meinen'], exp: 'helfen + Dativ · die Mutter → meiner Mutter.' },
    { a: 'kasus', p: 'Das Geschenk ist für ___ Vater.', o: ['meinen', 'meinem', 'mein'], exp: 'für + Akkusativ · der Vater → meinen Vater.' },
    { a: 'kasus', p: 'Ich wohne bei ___ Eltern.', o: ['meinen', 'meine', 'meiner'], exp: 'bei + Dativ · plural Dativ → meinen Eltern.' },
    { a: 'kasus', p: 'Kannst du ___ helfen? (me)', o: ['mir', 'mich', 'ich'], exp: 'helfen + Dativ → mir.' },
    { a: 'kasus', p: 'Ich rufe ___ an. (her)', o: ['sie', 'ihr', 'ihm'], exp: 'anrufen + Akkusativ → sie. (Dativ "ihr" is for helfen, danken …)' },
    { a: 'kasus', p: 'Ich danke ___ . (you, du)', o: ['dir', 'dich', 'du'], exp: 'danken + Dativ → dir.' },
    { a: 'kasus', p: 'Ich spreche jeden Tag mit ___ . (them)', o: ['ihnen', 'sie', 'ihr'], exp: 'mit + Dativ · sie (plural) → ihnen.' },
    { a: 'kasus', p: 'Ich gehe in ___ Park. (Wohin?)', o: ['den', 'dem', 'der'], exp: 'in + Wohin? (movement) → Akkusativ · der Park → den Park.' },
    { a: 'kasus', p: 'Ich bin in ___ Park. (Wo?)', o: ['dem', 'den', 'der'], exp: 'in + Wo? (place) → Dativ · der Park → dem Park (= im Park).' },
    { a: 'kasus', p: 'Ich komme aus ___ Türkei.', o: ['der', 'die', 'dem'], exp: 'aus + Dativ · die Türkei → der Türkei.' },
    { a: 'kasus', p: 'Ich besuche ___ Oma.', o: ['meine', 'meiner', 'meinem'], exp: 'besuchen + Akkusativ · die Oma → meine Oma (feminine: Akk = Nom).' },
    { a: 'kasus', p: 'Das Buch gefällt ___ . (me)', o: ['mir', 'mich', 'ich'], exp: 'gefallen + Dativ → mir.' },
    { a: 'kasus', p: 'Ich gebe ___ Kind einen Apfel.', o: ['dem', 'das', 'den'], exp: 'geben: person = Dativ (dem Kind), thing = Akkusativ (einen Apfel).' },
    { a: 'kasus', p: 'Ohne ___ Handy gehe ich nicht aus dem Haus.', o: ['mein', 'meinem', 'meinen'], exp: 'ohne + Akkusativ · das Handy → mein Handy (neuter: Akk = Nom).' },
    { a: 'kasus', p: 'Nach ___ Arbeit gehe ich nach Hause.', o: ['der', 'die', 'den'], exp: 'nach + Dativ · die Arbeit → der Arbeit.' },
    { a: 'kasus', p: 'Ich sehe ___ Mann.', o: ['den', 'dem', 'der'], exp: 'sehen + Akkusativ · der Mann → den Mann.' },
    { a: 'kasus', p: 'Hier gibt es ___ Supermarkt.', o: ['einen', 'ein', 'einem'], exp: 'es gibt + Akkusativ · der Supermarkt → einen Supermarkt.' },
    { a: 'kasus', p: 'Ich wünsche ___ viel Glück! (you, du)', o: ['dir', 'dich', 'du'], exp: 'jemandem (Dativ) etwas (Akk) wünschen → dir.' },
    { a: 'kasus', p: 'Ich wohne mit ___ Freundin zusammen.', o: ['meiner', 'meine', 'meinem'], exp: 'mit + Dativ · die Freundin → meiner Freundin.' },
    { a: 'kasus', p: 'Wir gehen zu ___ Arzt.', o: ['dem', 'den', 'der'], exp: 'zu + Dativ · der Arzt → dem Arzt (= zum Arzt).' }
  ],
  join: [
    { a: 'Ich lerne Deutsch.', b: 'Ich will in Deutschland arbeiten.', c: 'weil', de: 'Ich lerne Deutsch, weil ich in Deutschland arbeiten will.', alts: ['Weil ich in Deutschland arbeiten will, lerne ich Deutsch.'], why: 'weil → verb (will) at the end' },
    { a: 'Ich will in Deutschland arbeiten.', b: 'Ich lerne Deutsch.', c: 'deshalb', de: 'Ich will in Deutschland arbeiten, deshalb lerne ich Deutsch.', alts: ['Ich will in Deutschland arbeiten. Deshalb lerne ich Deutsch.'], why: 'deshalb → verb immediately (lerne ich)' },
    { a: 'Ich bleibe zu Hause.', b: 'Ich bin krank.', c: 'denn', de: 'Ich bleibe zu Hause, denn ich bin krank.', alts: [], why: 'denn = position 0 → normal order' },
    { a: 'Es regnet.', b: 'Wir gehen spazieren.', c: 'obwohl', de: 'Obwohl es regnet, gehen wir spazieren.', alts: ['Wir gehen spazieren, obwohl es regnet.'], why: 'obwohl → verb at the end (regnet)' },
    { a: 'Es regnet.', b: 'Wir gehen spazieren.', c: 'trotzdem', de: 'Es regnet, trotzdem gehen wir spazieren.', alts: ['Es regnet. Trotzdem gehen wir spazieren.', 'Es regnet, aber wir gehen trotzdem spazieren.'], why: 'trotzdem → verb immediately (gehen wir)' },
    { a: 'Ich weiß.', b: 'Meine Mutter ist immer glücklich.', c: 'dass', de: 'Ich weiß, dass meine Mutter immer glücklich ist.', alts: [], why: 'dass → verb at the end (ist)' },
    { a: 'Ich möchte wissen.', b: 'Hast du Geschwister?', c: 'ob', de: 'Ich möchte wissen, ob du Geschwister hast.', alts: [], why: 'yes/no question → ob + verb at the end' },
    { a: 'Ich habe Zeit.', b: 'Ich rufe meine Mutter an.', c: 'wenn', de: 'Wenn ich Zeit habe, rufe ich meine Mutter an.', alts: ['Ich rufe meine Mutter an, wenn ich Zeit habe.'], why: 'wenn-clause first → "habe, rufe ich" · an at the end' },
    { a: 'Ich war klein.', b: 'Wir hatten ein Haus auf dem Land.', c: 'als', de: 'Als ich klein war, hatten wir ein Haus auf dem Land.', alts: ['Wir hatten ein Haus auf dem Land, als ich klein war.'], why: 'als (once, past) → verb at the end (war)' },
    { a: 'Ich bin müde.', b: 'Ich habe schlecht geschlafen.', c: 'weil', de: 'Ich bin müde, weil ich schlecht geschlafen habe.', alts: ['Weil ich schlecht geschlafen habe, bin ich müde.'], why: 'Perfekt in a weil-clause → geschlafen habe' },
    { a: 'Ich stehe früh auf.', b: 'Ich muss arbeiten.', c: 'weil', de: 'Ich stehe früh auf, weil ich arbeiten muss.', alts: ['Weil ich arbeiten muss, stehe ich früh auf.'], why: 'modal at the very end: arbeiten muss' },
    { a: 'Meine Familie ist mir wichtig.', b: 'Ich besuche sie oft.', c: 'deshalb', de: 'Meine Familie ist mir wichtig, deshalb besuche ich sie oft.', alts: ['Meine Familie ist mir wichtig. Deshalb besuche ich sie oft.'], why: 'deshalb → besuche ich' },
    { a: 'Ich helfe meinen Eltern.', b: 'Ich will ihnen danken.', c: 'um … zu', de: 'Ich helfe meinen Eltern, um ihnen zu danken.', alts: [], why: 'same subject + purpose → um … zu + infinitive' },
    { a: 'Ich spreche jeden Tag Deutsch.', b: '(Ich versuche es.)', c: 'versuchen … zu', de: 'Ich versuche, jeden Tag Deutsch zu sprechen.', alts: ['Ich versuche jeden Tag, Deutsch zu sprechen.'], why: 'zu + infinitive at the very end' },
    { a: 'Ich trinke keinen Kaffee.', b: 'Ich trinke Tee.', c: 'sondern', de: 'Ich trinke keinen Kaffee, sondern Tee.', alts: ['Ich trinke keinen Kaffee, sondern ich trinke Tee.'], why: 'kein/nicht … sondern' },
    { a: 'Ich bin müde.', b: 'Ich lerne noch.', c: 'aber', de: 'Ich bin müde, aber ich lerne noch.', alts: [], why: 'aber = position 0 → normal order' }
  ]
};
