# -*- coding: utf-8 -*-
"""Generate the shared word data files from the canonical lists (and the home flashcards).

  js/lexicon.js         window.DC_LEXICON  - every word with the forms the trainers show
                        (verbs: Präteritum/Perfekt/noun, nouns: article/plural, adjectives:
                        Steigerung), English, Tamil, level, frequency rank, plus the example
                        sentence and note of the home flashcard for the same word. Used by the
                        Übersetzer & Wort-Explorer page (Uebersetzer.html).
  js/tamil-meanings.js  window.DC_TAMIL      - "cat|word" -> Tamil (transliteration) for the home
                        flashcards, whose own cards mostly have no Tamil field.

Nothing is invented here: every value is copied from the canonical lists
(Verb_Transformation_Trainer / Nomen_Trainer / Adjektiv_Adverb_Trainer) or the home cards.
Idempotent.   Run: python3 scripts/build_lexicon.py [--check]
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from check_vocab_sync import load, CANON, ROOT  # noqa: E402
from fill_home_forms import OBJ_RE, field  # noqa: E402

LEX = os.path.join(ROOT, 'js', 'lexicon.js')
TAMIL = os.path.join(ROOT, 'js', 'tamil-meanings.js')
HOME = os.path.join(ROOT, 'deutsch-coach.html')
HOME_CATS = {'v', 'n', 'adj', 'p', 'adv', 'x', 'q', 'pron', 'prep', 'konj', 'num'}


def ta_ai(e):
    """1 = Tamil drafted by AI, 2 = drafted by AI and marked uncertain (ta_src "ai?"), None = entered by a person."""
    src = str(e.get('ta_src', ''))
    return (2 if src == 'ai?' else 1) if src.startswith('ai') else None


def ta_text(e):
    ta = (e.get('ta') or '').strip()
    if not ta:
        return ''
    tr = (e.get('ta_translit') or '').strip()
    return ta + (' (' + tr + ')' if tr and tr not in ta else '')


def unescape(s):
    return json.loads('"' + s + '"') if s is not None else ''


def build():
    words, index = [], {}

    def add(entry):
        entry = {k: v for k, v in entry.items() if v not in ('', None)}
        index[(entry['c'], entry['w'].lower())] = entry
        words.append(entry)

    for e in load(*CANON['v'][:2]):
        add({'c': 'v', 'w': e['inf'], 'en': e.get('en'), 'ta': ta_text(e), 'pr': e.get('praeteritum'),
             'ex': e.get('ex'), 'exen': e.get('ex_en'), 'exta': e.get('ex_ta'), 'exai': 1 if e.get('ex_src') == 'ai' else None,
             'pp': e.get('perfekt'), 'noun': e.get('noun'), 'typ': e.get('typ'), 'lv': e.get('level'),
             'f': e.get('freq'), 'tai': ta_ai(e)})
    for e in load(*CANON['n'][:2]):
        if ('n', e['sg'].lower()) in index:
            continue
        add({'c': 'n', 'w': e['sg'], 'a': e.get('a'), 'pl': e.get('pl'), 'en': e.get('en'), 'ta': ta_text(e),
             'lv': e.get('level'), 'topic': e.get('topic'), 'f': e.get('freq'), 'tai': ta_ai(e)})
    for e in load(*CANON['a'][:2]):
        add({'c': 'adj', 'w': e['w'], 'komp': e.get('komp') or e.get('comp'), 'sup': e.get('sup'),
             'en': e.get('en'), 'ta': ta_text(e), 'lv': e.get('level'), 'f': e.get('freq'), 'tai': ta_ai(e)})

    # Home flashcards: example sentence + note for the same word; phrases and other words only the
    # lessons have are added as their own entries.
    html = open(HOME, encoding='utf-8').read()
    for m in OBJ_RE.finditer(html):
        obj = m.group(0)
        w, cat = field(obj, 'w'), field(obj, 'cat')
        if not w or cat not in HOME_CATS:
            continue
        w = unescape(w).strip()
        sg = re.sub(r'\([^)]*\)', '', w).strip()
        cat_key = 'adj' if cat == 'adj' else cat
        ex, mn, en = unescape(field(obj, 'ex')).strip(), unescape(field(obj, 'mn')).strip(), unescape(field(obj, 'en')).strip()
        e = index.get((cat_key, sg.lower()))
        if e:
            if ex and (not e.get('ex') or e.get('exai')):     # the home card's own example wins over an AI one
                e['ex'] = ex
                for k in ('exen', 'exta', 'exai'):
                    e.pop(k, None)
            if mn and 'mn' not in e and not mn.startswith('<b>Nomen:</b>'):
                e['mn'] = mn
            continue
        if not en:
            continue
        add({'c': cat_key, 'w': sg, 'a': unescape(field(obj, 'a')).strip(), 'pl': unescape(field(obj, 'p')).strip(),
             'pr': unescape(field(obj, 'pr')).strip(), 'pp': unescape(field(obj, 'pp')).strip(),
             'komp': unescape(field(obj, 'comp')).strip(), 'sup': unescape(field(obj, 'sup')).strip(),
             'en': en, 'ex': ex, 'mn': mn, 'src': 'home'})

    head = ('/* GENERATED by scripts/build_lexicon.py from the canonical word lists and the home flashcards'
            ' - do not edit by hand. */\n')
    lex = head + 'window.DC_LEXICON = ' + json.dumps(words, ensure_ascii=False, separators=(',', ':')) + ';\n'
    tamil = {e['c'] + '|' + e['w']: e['ta'] for e in words if e.get('ta')}
    ai = {e['c'] + '|' + e['w']: e['tai'] for e in words if e.get('ta') and e.get('tai')}
    ta = (head + 'window.DC_TAMIL = ' + json.dumps(tamil, ensure_ascii=False, separators=(',', ':')) + ';\n'
          + '/* Tamil drafted by AI, labelled 🤖 in the app (2 = marked uncertain) */\nwindow.DC_TAMIL_AI = ' + json.dumps(ai, ensure_ascii=False, separators=(',', ':'), sort_keys=True) + ';\n')
    return lex, ta, len(words), len(tamil)


def main():
    lex, ta, n, nt = build()
    cur = [open(p, encoding='utf-8').read() if os.path.exists(p) else '' for p in (LEX, TAMIL)]
    if '--check' in sys.argv:
        if cur != [lex, ta]:
            print('js/lexicon.js / js/tamil-meanings.js are out of date (run scripts/build_lexicon.py)')
            sys.exit(1)
        print('OK: js/lexicon.js and js/tamil-meanings.js are up to date (%d words, %d with Tamil).' % (n, nt))
        return
    open(LEX, 'w', encoding='utf-8').write(lex)
    open(TAMIL, 'w', encoding='utf-8').write(ta)
    print('wrote js/lexicon.js (%d words, %d KB) and js/tamil-meanings.js (%d Tamil meanings, %d KB)' % (
        n, len(lex.encode()) // 1024, nt, len(ta.encode()) // 1024))


if __name__ == '__main__':
    main()
